#ifndef _ASSEMBLY_STORAGE_MAP_HPP
#define _ASSEMBLY_STORAGE_MAP_HPP

struct _ASSEMBLY_STORAGE_MAP;
typedef struct _ASSEMBLY_STORAGE_MAP ASSEMBLY_STORAGE_MAP;
typedef struct _ASSEMBLY_STORAGE_MAP *PASSEMBLY_STORAGE_MAP;

#endif // _ASSEMBLY_STORAGE_MAP_HPP