#ifndef _FLT_OPERATION_REGISTRATION__HPP
#define _FLT_OPERATION_REGISTRATION__HPP

#include "IOCTLKernel.hpp"

struct _FLT_OPERATION_REGISTRATION
{
    UCHAR MajorFunction;
    FLT_OPERATION_REGISTRATION_FLAGS Flags;
    PFLT_PRE_OPERATION_CALLBACK PreOperation;
    PFLT_POST_OPERATION_CALLBACK PostOperation;
    PVOID Reserved1;
};

#endif // _FLT_OPERATION_REGISTRATION__HPP