#ifndef _FLT_POST_OPERATION_STATUS_HPP
#define _FLT_POST_OPERATION_STATUS_HPP

typedef enum _FLT_POST_OPERATION_STATUS
{
    FLT_POSTOP_FINISHED_PROCESSING,
    FLT_POSTOP_MORE_PROCESSING_REQUIRED
} FLT_POST_OPERATION_STATUS;

typedef FLT_POST_OPERATION_STATUS (FLTAPI *PFLT_POST_OPERATION_CALLBACK)(
    PFLT_CALLBACK_DATA Data,
    PCFLT_RELATED_OBJECTS FltObjects,
    PVOID CompletionContext,
    FLT_POST_OPERATION_FLAGS Flags);

#endif // _FLT_POST_OPERATION_STATUS_HPP