#ifndef _FLT_PREOP_CALLBACK_STATUS_HPP
#define _FLT_PREOP_CALLBACK_STATUS_HPP

typedef enum _FLT_PREOP_CALLBACK_STATUS
{
    FLT_PREOP_SUCCESS_WITH_CALLBACK,
    FLT_PREOP_SUCCESS_NO_CALLBACK,
    FLT_PREOP_PENDING,
    FLT_PREOP_DISALLOW_FAST_IO,
    FLT_PREOP_COMPLETE,
    FLT_PREOP_SYNCHRONIZE
} FLT_PREOP_CALLBACK_STATUS;

typedef FLT_PREOP_CALLBACK_STATUS (FLTAPI *PFLT_PRE_OPERATION_CALLBACK)(
    PFLT_CALLBACK_DATA Data,
    PCFLT_RELATED_OBJECTS FltObjects,
    PVOID *CompletionContext);

#endif // _FLT_PREOP_CALLBACK_STATUS_HPP