#ifndef _PROCESS_WS_WATCH_INFORMATION_HPP
#define _PROCESS_WS_WATCH_INFORMATION_HPP

struct _PROCESS_WS_WATCH_INFORMATION
{
    PVOID FaultingPc;
    PVOID FaultingVa;
};

#endif // _PROCESS_WS_WATCH_INFORMATION_HPP