#ifndef _PTL_DRIVE_LITTER_CURDIR_HPP
#define _PTL_DRIVE_LITTER_CURDIR_HPP

struct _RTL_DRIVE_LETTER_CURDIR
{
    WORD Flags;
    WORD Length;
    ULONG TimeStamp;
};

#endif // _PTL_DRIVE_LITTER_CURDIR_HPP