#ifndef _SE_AUDIT_PROCESS_CREATION_INFO_HPP
#define _SE_AUDIT_PROCESS_CREATION_INFO_HPP

struct _SE_AUDIT_PROCESS_CREATION_INFO
{
    POBJECT_NAME_IMFORMATION ImageFileName;
};

#endif // _SE_AUDIT_PROCESS_CREATION_INFO_HPP