#ifndef IOCTLKERNEL_HPP
#define IOCTLKERNEL_HPP

#include <windows.h>

#define FLTAPI __stdcall
typedef unsigned long FLT_OPERATION_REGISTRATION_FLAGS;
typedef unsigned long FLT_CALLBACK_DATA_FLAGS;

typedef ULONG FLT_POST_OPERATION_FLAGS;

typedef struct _FLT_INSTANCE *PFLT_INSTANCE;
typedef short CSHORT;
typedef CSHORT *PCSHORT;

#ifdef _WIN64

#define POINTER_ALIGNMENT DECLSPEC_ALIGN(8)
#else

#define POINTER_ALIGNMENT
#endif

#include "typedef/typedef.hpp"

#include "_UNICODE_STRING.hpp"
#include "_IO_CLIENT_EXTENSION.hpp"
#include "_FS_FILTER_CALLBACKS.hpp"
#include "_DRIVER_EXTENSION.hpp"
#include "_FAST_IO_DISPATCH.hpp"
#include "_DRIVER_OBJECT.hpp"
#include "_DISPATCHER_HEADER.hpp"
#include "_KDEVICE_QUEUE.hpp"
#include "_KDPC.hpp"
#include "_KEVENT.hpp"
#include "_IO_STATUS_BLOCK.hpp"
#include "_SECTION_OBJECT_POINTERS.hpp"
#include "_KPROCESSOR_MODE.hpp"
#include "_DEVICE_OBJECT.hpp"
#include "_IRP.hpp"
#include "_IO_TIMER.hpp"
#include "_VPB.hpp"
#include "_FLT_OPERATION_REGISTRATION_.hpp"
#include "_KGDTENTRY.hpp"
#include "_KIDTENTRY.hpp"
#include "_KEXECUTE_OPTIONS.hpp"
#include "_KPROCESS.hpp"
#include "_EX_PUSH_LOCK.hpp"
#include "_EX_RUNDOWN_REF.hpp"
#include "_KAPC_STATE.hpp"
#include "_KWAIT_BLOCK.hpp"
#include "_KGATE.hpp"
#include "_KQUEUE.hpp"
#include "_KDPC.hpp"
#include "_KTIMER.hpp"
#include "_KTRAP_FRAME.hpp"
#include "_KAPC.hpp"
#include "_DESCRIPTOR.hpp"
#include "_KSPECIAL_REGISTERS.hpp"
#include "_KPROCESSOR_STATE.hpp"
#include "_KSPIN_LOCK_QUEUE.hpp"
#include "_CACHED_KSTACK_LIST.hpp"
#include "_KNODE.hpp"
#include "_POOL_TYPE.hpp"
#include "_GENERAL_LOOKASIDE.hpp"
#include "_PP_LOOKASIDE_LIST.hpp"
#include "_GENERAL_LOOKASIDE_POOL.hpp"
#include "_KDPC_DATA.hpp"
#include "_KEVENT.hpp"
#include "_KDEVICE_QUEUE.hpp"
#include "_DEVOBJ_EXTENSION.hpp"
#include "_FX_SAVE_AREA.hpp"
#include "_PPM_IDLE_STATE.hpp"
#include "_PROCESSOR_IDLE_TIMES.hpp"
#include "_PPM_PREF_STATE.hpp"
#include "_PPM_PREF_STATES.hpp"
#include "_PROCESSOR_POWER_STATE.hpp"
#include "_KPRCB.hpp"
#include "_KSEMAPHORE.hpp"
#include "_KTHREAD.hpp"
#include "_FAST_MUTEX.hpp"
#include "_CLIENT_ID.hpp"
#include "_HANDLE_TRACE_DB_ENTRY.hpp"
#include "_HANDLE_TRACE_DEBUG_INFO.hpp"
#include "_HANDLE_TABLE_ENTRY_INFO.hpp"
#include "_HANDLE_TABLE_ENTRY.hpp"
#include "_HANDLE_TABLE.hpp"
#include "_EX_FAST_REF.hpp"
#include "_PSP_RATE_APC.hpp"
#include "_TERMINATION_PORT.hpp"
#include "_PS_CLIENT_SECURITY_CONTEXT.hpp"
#include "_ETHREAD.hpp"
#include "_MMADDRESS_NODE.hpp"
#include "_MM_AVL_TABLE.hpp"
#include "_JOB_ACCESS_STATE.hpp"
#include "_OWNER_ENTRY.hpp"
#include "_ERESOURCE.hpp"
#include "_EJOB.hpp"
#include "_EPROCESS_QUOTA_ENTRY.hpp"
#include "_EPROCESS_QUOTA_BLOCK.hpp"
#include "_PROCESS_WS_WATCH_INFORMATION.hpp"
#include "_PAGEFAULT_HISTORY.hpp"
#include "_HARDWARE_PTE.hpp"
#include "_PEB_LDR_DATA.hpp"
#include "_CURDIR.hpp"
#include "_STRING.hpp"
#include "_PTL_DRIVE_LITTER_CURDIR.hpp"
#include "_RTL_USER_PROCESS_PARAMETERS.hpp"
#include "_PEB_FREE_BLOCK.hpp"
#include "_ACTIVATION_CONTEXT_DATA.hpp"
#include "_ASSEMBLY_STORAGE_MAP.hpp"
#include "_FLS_CALLBACK_INFO.hpp"
#include "_PEB.hpp"
#include "_OBJECT_NAME_IMFORMATION.hpp"
#include "_SE_AUDIT_PROCESS_CREATION_INFO.hpp"
#include "_MMSUPPORT_FLAGS.hpp"
#include "_MMWSLE.hpp"
#include "_MMWSLE_NONDIRECT_HASH.hpp"
#include "_MMWSLE_HASH.hpp"
#include "_MMSUPPORT.hpp"
#include "_ALPC_PROCESS_CONTEXT.hpp"
#include "_EPROCESS.hpp"
#include "_MDL.hpp"
#include "_IO_STATUS_BLOCK.hpp"
#include "_POWER_CHANNEL_SUMMARY.hpp"
#include "_SECTION_OBJECT_POINTERS.hpp"
#include "_IO_COMPLETION_CONTEXT.hpp"
#include "_FILE_OBJECT.hpp"
#include "_DEVICE_OBJECT_POWER_EXTENSION.hpp"
#include "_SECURITY_SUBJECT_CONTEXT.hpp"
#include "_ACCESS_STATE.hpp"
#include "_IO_SECURITY_CONTEXT.hpp"
#include "_FILE_INFORMATION_CLASS.hpp"
#include "_FLT_PARAMETERS.hpp"
#include "_FLT_IO_PARAMETER_BLOCK.hpp"
#include "_KPROCESSOR_MODE.hpp"
#include "_FLT_CALLBACK_DATA.hpp"
#include "_FLT_RELATED_OBJECTS.hpp"
#include "_FLT_PREOP_CALLBACK_STATUS.hpp"
#include "_FLT_POST_OPERATION_STATUS.hpp"
#include "_FLT_OPERATION_REGISTRATION_.hpp"

#endif // IOCTLKERNEL_HPP