#ifndef _FSCTL_CSV_QUERY_DOWN_LEVEL_FILE_SYSTEM_CHARACTERISTICS_HPP
#define _FSCTL_CSV_QUERY_DOWN_LEVEL_FILE_SYSTEM_CHARACTERISTICS_HPP

#include <windows.h>

typedef struct _FSCTL_CSV_QUERY_DOWN_LEVEL_FILE_SYSTEM_CHARACTERISTICS_OUTPUT
{
    ULONG VolumeCharacteristics;
} FSCTL_CSV_QUERY_DOWN_LEVEL_FILE_SYSTEM_CHARACTERISTICS_OUTPUT, *PFSCTL_CSV_QUERY_DOWN_LEVEL_FILE_SYSTEM_CHARACTERISTICS_OUTPUT;

typedef struct _CSV_QUERY_DOWN_LEVEL_FILE_SYSTEM_CHARACTERISTICS_OUTPUT
{
    ULONG VolumeCharacteristics;
} CSV_QUERY_DOWN_LEVEL_FILE_SYSTEM_CHARACTERISTICS_OUTPUT, *PCSV_QUERY_DOWN_LEVEL_FILE_SYSTEM_CHARACTERISTICS_OUTPUT;

#define CTL_CODE(DeviceType, Function, Method, Access)(((DeviceType) << 16) | ((Access) << 14) | ((Function) << 2) | (Method))

#define FILE_DEVICE_FILE_SYSTEM 0x00000009

#define METHOD_BUFFERED 0

#define FILE_ANY_ACCESS 0

#ifndef FILE_CASE_SENSITIVE_SEARCH
#define FILE_CASE_SENSITIVE_SEARCH 0x00000001
#define FILE_CASE_PERSERVED_NAME   0x00000002
#define FILE_UNICODE_ON_DISK       0x00000004
#define FILE_PERSISTENT_ACLS       0x00000008
#endif

#define FSCTL_CSV_QUERY_DOWN_LEVEL_FILE_SYSTEM_CHARACTERISTICS \
    CTL_CODE(FILE_DEVICE_FILE_SYSTEM, 184, METHOD_BUFFERED, FILE_ANY_ACCESS)

#endif // _FSCTL_CSV_QUERY_DOWN_LEVEL_FILE_SYSTEM_CHARACTERISTICS_HPP