#ifndef HMAC_HPP
#define HMAC_HPP

#include <string>
#include <cstdint>

extern "C"
{
    #include <string.h>
    #include <stdint.h>
}

#define __R_HASH_BASED_MESSAGE_AUTHENTICATION_CODE_ROT_RIGHT_FUNCTION__(_HMAC_WORD, BITS) [&]() { return (((_HMAC_WORD) >> (BITS)) | ((_HMAC_WORD) << (32 - (BITS)))); }()
#define __R_HASH_BASED_MESSAGE_AUTHENTICATION_CODE_CH_FUNCTION__(_X, _Y, _Z) [&]() { return (((_X) & (_Y)) ^ ((~(_X)) & (_Z))); }()
#define __R_HASH_BASED_MESSAGE_AUTHENTICATION_CODE_MAJ_FUNCTION__(_X, _Y, _Z) [&]() { return (((_X) & (_Y)) ^ ((_X) & (_Z)) ^ ((_Y) & (_Z))); }()
#define __R_HASH_BASED_MESSAGE_AUTHENTICATION_CODE_EP0_FUNCTION__(_X) [&]() { return (__R_HASH_BASED_MESSAGE_AUTHENTICATION_CODE_ROT_RIGHT_FUNCTION__(_X, 2) ^ __R_HASH_BASED_MESSAGE_AUTHENTICATION_CODE_ROT_RIGHT_FUNCTION__(_X, 13) ^ __R_HASH_BASED_MESSAGE_AUTHENTICATION_CODE_ROT_RIGHT_FUNCTION__(_X, 22)); }()
#define __R_HASH_BASED_MESSAGE_AUTHENTICATION_CODE_EP1_FUNCTION__(_X) [&]() { return (__R_HASH_BASED_MESSAGE_AUTHENTICATION_CODE_ROT_RIGHT_FUNCTION__(_X, 6) ^ __R_HASH_BASED_MESSAGE_AUTHENTICATION_CODE_ROT_RIGHT_FUNCTION__(_X, 11) ^ __R_HASH_BASED_MESSAGE_AUTHENTICATION_CODE_ROT_RIGHT_FUNCTION__(_X, 25)); }()
#define __R_HASH_BASED_MESSAGE_AUTHENTICATION_CODE_SIG0_FUNCTION__(_X) [&]() { return (__R_HASH_BASED_MESSAGE_AUTHENTICATION_CODE_ROT_RIGHT_FUNCTION__(_X, 7) ^ __R_HASH_BASED_MESSAGE_AUTHENTICATION_CODE_ROT_RIGHT_FUNCTION__(_X, 18) ^ ((_X) >> 3)); }()
#define __R_HASH_BASED_MESSAGE_AUTHENTICATION_CODE_SIG1_FUNCTION__(_X) [&]() { return (__R_HASH_BASED_MESSAGE_AUTHENTICATION_CODE_ROT_RIGHT_FUNCTION__(_X, 17) ^ __R_HASH_BASED_MESSAGE_AUTHENTICATION_CODE_ROT_RIGHT_FUNCTION__(_X, 19) ^ ((_X) >> 10)); }()

struct __HMAC_VER_SHA_256_CONTEXT
{
    uint8_t DATA[64];
    uint32_t DATA_LEN;
    uint64_t BIT_LEN;
    uint32_t STATE[8];
};

#define __R_HASH_BASED_MESSAGE_AUTHENTICATION_CODE_TRANSFORM_FUNCTION__(CTX, DATA) [&]() {\
    const uint32_t K[64] = {\
        0x428a2f98,0x71374491,0xb5c0fbcf,0xe9b5dba5,0x3956c25b,0x59f111f1,0x923f82a4,0xab1c5ed5,\
        0xd807aa98,0x12835b01,0x243185be,0x550c7dc3,0x72be5d74,0x80deb1fe,0x9bdc06a7,0xc19bf174,\
        0xe49b69c1,0xefbe4786,0x0fc19dc6,0x240ca1cc,0x2de92c6f,0x4a7484aa,0x5cb0a9dc,0x76f988da,\
        0x983e5152,0xa831c66d,0xb00327c8,0xbf597fc7,0xc6e00bf3,0xd5a79147,0x06ca6351,0x14292967,\
        0x27b70a85,0x2e1b2138,0x4d2c6dfc,0x53380d13,0x650a7354,0x766a0abb,0x81c2c92e,0x92722c85,\
        0xa2bfe8a1,0xa81a664b,0xc24b8b70,0xc76c51a3,0xd192e819,0xd6990624,0xf40e3585,0x106aa070,\
        0x19a4c116,0x1e376c08,0x2748774c,0x34b0bcb5,0x391c0cb3,0x4ed8aa4a,0x5b9cca4f,0x682e6ff3,\
        0x748f82ee,0x78a5636f,0x84c87814,0x8cc70208,0x90befffa,0xa4506ceb,0xbef9a3f7,0xc67178f2};\
    uint32_t A, B, C, D, E, F, G, H, T1, T2, M[64];\
    for (I = 0, J = 0; I < 16; ++I, J += 4)\
    {\
        M[I] = (DATA[J] << 24) | (DATA[J + 1] << 16) | (DATA[J + 2] << 8) | (DATA[J + 3]);\
    }\
    for (; I < 64; ++I)\
    {\
        M[I] = __R_HASH_BASED_MESSAGE_AUTHENTICATION_CODE_SIG1_FUNCTION__(M[I - 2]) + M[I - 7] + __R_HASH_BASED_MESSAGE_AUTHENTICATION_CODE_SIG0_FUNCTION__(M[I - 15]) + M[I - 16];\
    }\
    A = CTX->STATE[0]; B = CTX->STATE[1]; C = CTX->STATE[2]; D = CTX->STATE[3];\
    E = CTX->STATE[4]; F = CTX->STATE[5]; G = CTX->STATE[6]; H = CTX->STATE[7];\
    for (I = 0; I < 64; ++I)\
    {\
        T1 = H + __R_HASH_BASED_MESSAGE_AUTHENTICATION_CODE_EP1_FUNCTION__(E) + __R_HASH_BASED_MESSAGE_AUTHENTICATION_CODE_CH_FUNCTION__(E, F, G) + K[I] + M[I];\
        T2 = __R_HASH_BASED_MESSAGE_AUTHENTICATION_CODE_EP0_FUNCTION__(A) + __R_HASH_BASED_MESSAGE_AUTHENTICATION_CODE_MAJ_FUNCTION__(A, B, C);\
        H = G; G = F; F = E; E = D + T1; D = C; C = B; B = A; A = T1 + T2;\
    }\
    CTX->STATE[0] += A; CTX->STATE[1] += B; CTX->STATE[2] += C; CTX->STATE[3] += D;\
    CTX->STATE[4] += E; CTX->STATE[5] += F; CTX->STATE[6] += G; CTX->STATE[7] += H;\
    return; }()
#define __R_HASH_BASED_MESSAGE_AUTHENTICATION_CODE_INIT_FUNCTION__(CTX) [&]() {\
    CTX->DATA_LEN = 0; CTX->BIT_LEN = 0;\
    CTX->STATE[0] = 0x6a09e667; CTX->STATE[1] = 0xbb67ae85; CTX->STATE[2] = 0x3c6ef372; CTX->STATE[3] = 0xa54ff53a;\
    CTX->STATE[4] = 0x510e527f; CTX->STATE[5] = 0x9b05688c; CTX->STATE[6] = 0x1f83d9ab; CTX->STATE[7] = 0x5be0cd19;\
    return; }()
#define __R_HASH_BASED_MESSAGE_AUTHENTICATION_CODE_UPDATE_FUNCTION__(CTX, DATA, LEN) [&]() {\
    for (size_t I = 0; I < LEN; ++I)\
    {\
        CTX->DATA[CTX->DATA_LEN++] = DATA[I];\
        CTX->DATA_LEN++;\
        if (CTX->DATA_LEN == 64)\
        {\
            __R_HASH_BASED_MESSAGE_AUTHENTICATION_CODE_TRANSFORM_FUNCTION__(CTX, CTX->DATA);\
            CTX->BIT_LEN += 512;\
            CTX->DATA_LEN = 0;\
        }\
    }\
    return; }()
#define __R_HASH_BASED_MESSAGE_AUTHENTICATION_CODE_FINALIZE_FUNCTION__(CTX, HASH) [&]() {\
    uint32_t I = CTX->DATA_LEN;\
    if (CTX->DATA_LEN < 56)\
    {\
        CTX->DATA[I++] = 0x80;\
        while (I < 56) CTX->DATA[I++] = 0x00;\
    }\
    else\
    {\
        CTX->DATA[I++] = 0x80;\
        while (I < 64) CTX->DATA[I++] = 0x00;\
        __R_HASH_BASED_MESSAGE_AUTHENTICATION_CODE_TRANSFORM_FUNCTION__(CTX, CTX->DATA);\
        memset(CTX->DATA, 0, 56);\
    }\
    CTX->BIT_LEN += CTX->DATA_LEN * 8;\
    CTX->DATA[63] = CTX->BIT_LEN; CTX->DATA[62] = CTX->BIT_LEN >> 8;\
    CTX->DATA[61] = CTX->BIT_LEN >> 16; CTX->DATA[60] = CTX->BIT_LEN >> 24;\
    CTX->DATA[59] = CTX->BIT_LEN >> 32; CTX->DATA[58] = CTX->BIT_LEN >> 40;\
    CTX->DATA[57] = CTX->BIT_LEN >> 48; CTX->DATA[56] = CTX->BIT_LEN >> 56;\
    __R_HASH_BASED_MESSAGE_AUTHENTICATION_CODE_TRANSFORM_FUNCTION__(CTX, CTX->DATA);\
    for (I = 0; I < 4; ++I)\
    {\
        HASH[I]     = (CTX->STATE[0] >> (24 - I * 8)) & 0x000000ff;\
        HASH[I + 4] = (CTX->STATE[1] >> (24 - I * 8)) & 0x000000ff;\
        HASH[I + 8] = (CTX->STATE[2] >> (24 - I * 8)) & 0x000000ff;\
        HASH[I + 12] = (CTX->STATE[3] >> (24 - I * 8)) & 0x000000ff;\
        HASH[I + 16] = (CTX->STATE[4] >> (24 - I * 8)) & 0x000000ff;\
        HASH[I + 20] = (CTX->STATE[5] >> (24 - I * 8)) & 0x000000ff;\
        HASH[I + 24] = (CTX->STATE[6] >> (24 - I * 8)) & 0x000000ff;\
        HASH[I + 28] = (CTX->STATE[7] >> (24 - I * 8)) & 0x000000ff;\
    }\
    return; }()
#define __R_HASH_BASED_MESSAGE_AUTHENTICATION_CODE_SHA_256_FUNCTION__(DATA, LEN, OUTPUT) [&]() {\
    __R_HASH_BASED_MESSAGE_AUTHENTICATION_CODE_CONTEXT CTX;\
    __R_HASH_BASED_MESSAGE_AUTHENTICATION_CODE_INIT_FUNCTION__(&CTX);\
    __R_HASH_BASED_MESSAGE_AUTHENTICATION_CODE_UPDATE_FUNCTION__(&CTX, DATA, LEN);\
    __R_HASH_BASED_MESSAGE_AUTHENTICATION_CODE_FINALIZE_FUNCTION__(&CTX, OUTPUT);\
    return; }()

#define __R_HASH_BASED_MESSAGE_AUTHENTICATION_CODE__SHA_256_BLOCK_SIZE 64
#define __R_HASH_BASED_MESSAGE_AUTHENTICATION_CODE__SHA_256_DIGEST_SIZE 32

#define __R_HASH_BASED_MESSAGE_AUTHENTICATION_CODE_FUNCTION__(KEY, KEY_LEN, MESSAGE, MESSAGE_LEN, OUTPUT)[&]() {\
    uint8_t PREPARED_KEY[__R_HASH_BASED_MESSAGE_AUTHENTICATION_CODE__SHA_256_BLOCK_SIZE] = {0};\
    if (KEY_LEN > __R_HASH_BASED_MESSAGE_AUTHENTICATION_CODE__SHA_256_BLOCK_SIZE)\
    {\
        __R_HASH_BASED_MESSAGE_AUTHENTICATION_CODE_SHA_256_FUNCTION__(KEY, KEY_LEN, PREPARED_KEY, __R_HASH_BASED_MESSAGE_AUTHENTICATION_CODE__SHA_256_BLOCK_SIZE);\
    }\
    else\
    {\
        memcpy(PREPARED_KEY, KEY, KEY_LEN);\
    }\
    uint8_t I_PAD[__R_HASH_BASED_MESSAGE_AUTHENTICATION_CODE__SHA_256_BLOCK_SIZE];\
    uint8_t O_PAD[__R_HASH_BASED_MESSAGE_AUTHENTICATION_CODE__SHA_256_BLOCK_SIZE];\
    for (int I = 0; I < __R_HASH_BASED_MESSAGE_AUTHENTICATION_CODE__SHA_256_BLOCK_SIZE; ++I)\
    {\
        I_PAD[I] = PREPARED_KEY[I] ^ 0x36;\
        O_PAD[I] = PREPARED_KEY[I] ^ 0x5c;\
    }\
    uint8_t INNER_HASH[__R_HASH_BASED_MESSAGE_AUTHENTICATION_CODE__SHA_256_DIGEST_SIZE];\
    __HMAC_VER_SHA_256_CONTEXT INNER_CTX;\
    __R_HASH_BASED_MESSAGE_AUTHENTICATION_CODE_INIT_FUNCTION__(&INNER_CTX);\
    __R_HASH_BASED_MESSAGE_AUTHENTICATION_CODE_UPDATE_FUNCTION__(&INNER_CTX, MESSAGE, MESSAGE_LEN);\
    __R_HASH_BASED_MESSAGE_AUTHENTICATION_CODE_FINALIZE_FUNCTION__(&INNER_CTX, INNER_HASH);\
    __HMAC_VER_SHA_256_CONTEXT OUTER_CTX;\
    __R_HASH_BASED_MESSAGE_AUTHENTICATION_CODE_INIT_FUNCTION__(&OUTER_CTX);\
    __R_HASH_BASED_MESSAGE_AUTHENTICATION_CODE_UPDATE_FUNCTION__(&OUTER_CTX, O_PAD, __R_HASH_BASED_MESSAGE_AUTHENTICATION_CODE__SHA_256_BLOCK_SIZE);\
    __R_HASH_BASED_MESSAGE_AUTHENTICATION_CODE_FINALIZE_FUNCTION__(&OUTER_CTX, OUTPUT);\
    return; }()

#endif // HMAC_HPP